### ISSUE TITLE
Generate string conversion methods from existent NS_ENUM declarations

### ISSUE THREAD

**Issue by hokster7** [rentzsch/JREnum#12]
e.g. Looking at `UIImagePickerController`, I want to benefit from printing out strings that correspond to the values of `UIImagePickerControllerSourceType`, or `UIImagePickerControllerQualityType` for example.

Since it's already been declared in UIKit it's unclear to me how JREnum could inspect such a declaration and generate convertors.

**Comment by rentzsch** [comment]
Yeah, that would be nice. Sadly as you've noticed they've already been declared so there's nothing JREnum can do.

**Comment by hokster7** [comment]
Ach, what a shame. :(
