### ISSUE TITLE
Xcode 9 gives zillions of errors

### ISSUE THREAD

**Issue by alakoring** [rentzsch/JREnum#14]
When I use the latest Xcode 9 beta, I get errors like

/GameConstants.h:31:1: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JREnumDeclare(AttitudeColor,
^
In file included from GameConstants.h:15:
Utilities/JREnum.h:30:48: note: expanded from macro 'JREnumDeclare'
    extern NSDictionary* ENUM_TYPENAME##ByValue();  \

Is this something that can be addressed in the macros?

**Comment by rentzsch** [comment]
Hey David,

I'll probably be able to figure something out but my current Mac is still on 10.11 which can't run Xcode 9. My new Mac is scheduled to arrive Jul 5, then I'll download Xcode 9 and see what I can do.

The quickest+hackiest way to work around this immediately is disable that specific warning.

**Comment by rentzsch** [comment]
Got my MacBook early. This is fixed in v1.2.

**Comment by alakoring** [comment]
Yes, does the trick. Thank you!
