### ISSUE TITLE
Git tags needed for CocoaPods spec.

### ISSUE THREAD

**Issue by insanehunter** [rentzsch/JREnum#2]
I've created a [CocoaPods spec for JREnum](https://github.com/CocoaPods/Specs/blob/master/JREnum/0.2/JREnum.podspec), but it currently fails validation as it points to the latest commit instead of a tag.

Could you please add a (presumably) 0.2 tag to the current revision?

Thank you.

**Comment by rentzsch** [comment]
Done.

**Comment by insanehunter** [comment]
Thank you very much!
