### ISSUE TITLE
JREnumDeclare causing compiler "Unused variable" warnings.

### ISSUE THREAD

**Issue by mralexgray** [rentzsch/JREnum#3]
`… Unused variable '_AZQuadrant_constants_string'`

i tried wrapping the whole macro in

`#pragma clang diagnostic push
# pragma clang diagnostic ignored "-Wunused-value"

"JREnumDeclare…"
# pragma clang diagnostic pop`

or just wrapping the 

`static NSString *_##ENUM_TYPENAME##_constants_string = @"" #ENUM_CONSTANTS;`

line, but didn't help. actually, tried wrapping the single line with  the weird `_Pragma( blah blah blah) format - that "supposedly" works with Macros.

I finally tied to just convert the whole thing to a straight function… but i can't figure out what the hell  `##ByValue();` etc are doing.

any advice?

**Comment by rentzsch** [comment]
Yeah I got a repro here. I'm pretty sure this didn't used to trigger a warning.

`_##ENUM_TYPENAME##_constants_string` is just a way to pass the enum string from where it was declared (usually a .h file) to where it can be implemented (usually in a .m file).

**Comment by rentzsch** [comment]
Oh I forgot to mention: I discovered a couple of clang versions back `_Pragma("clang diagnostic ignored \"-Wunused-value\"")` stopped working. I suspect a regression, and I'm surprised it's not fixed yet.

**Comment by rentzsch** [comment]
Oops, forgot to mark this one closed. It was fixed in https://github.com/rentzsch/JREnum/commit/4398e3f49ec44fb12ee3d1f29ae7fd9ab57b918f
